//------------------------------------------------------ // catch
//------------------------------------------------------ // Вызов .catch(f) – это сокращённый, «укороченный» вариант
.then(null, f).

let promise = new Promise((resolve, reject) => { setTimeout(() => reject(new Error("Ошибка!")), 1000); });

promise.catch(alert); // выведет "Error: Ошибка!" спустя одну секунду






